definitions:
  go-gravatar_api_v1.GetProfileResponse:
    properties:
      code:
        type: integer
      data:
        $ref: '#/definitions/go-gravatar_api_v1.GetProfileResponseData'
      message:
        type: string
    type: object
  go-gravatar_api_v1.GetProfileResponseData:
    properties:
      email:
        example: username@example.lan
        type: string
      nickname:
        example: Billy
        type: string
      userId:
        example: ExWFdl17WS
        type: string
      username:
        example: username
        type: string
    type: object
  go-gravatar_api_v1.LoginRequest:
    properties:
      password:
        example: password
        type: string
      username:
        example: username
        type: string
    required:
    - password
    - username
    type: object
  go-gravatar_api_v1.LoginResponse:
    properties:
      code:
        type: integer
      data:
        $ref: '#/definitions/go-gravatar_api_v1.LoginResponseData'
      message:
        type: string
    type: object
  go-gravatar_api_v1.LoginResponseData:
    properties:
      accessToken:
        type: string
    type: object
  go-gravatar_api_v1.RegisterRequest:
    properties:
      email:
        example: username@example.lan
        type: string
      password:
        example: password
        type: string
    required:
    - email
    - password
    type: object
  go-gravatar_api_v1.ResetRequest:
    properties:
      email:
        example: username@example.lan
        type: string
    required:
    - email
    type: object
  go-gravatar_api_v1.Response:
    properties:
      code:
        type: integer
      data: {}
      message:
        type: string
    type: object
  go-gravatar_api_v1.UpdateProfileRequest:
    properties:
      email:
        example: username@example.lan
        type: string
      nickname:
        example: Billy
        type: string
      username:
        example: username
        type: string
    type: object
host: localhost:8000
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: This is a sample server celler server.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Nunu Example API
  version: 1.0.0
paths:
  /avatar:
    delete:
      description: 删除头像
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/go-gravatar_api_v1.Response'
      security:
      - Bearer: []
      summary: 删除头像
      tags:
      - 头像模块
    put:
      consumes:
      - multipart/form-data
      description: 修改头像
      parameters:
      - description: avatar
        in: formData
        name: file
        required: true
        type: file
      - description: image form other source
        in: formData
        name: jsonData
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/go-gravatar_api_v1.Response'
      security:
      - Bearer: []
      summary: 修改头像
      tags:
      - 头像模块
  /avatar/{hash}:
    get:
      description: 获取头像
      parameters:
      - description: email hash
        in: path
        name: hash
        required: true
        type: string
      produces:
      - image/jpeg
      - ' image/png'
      - ' image/webp'
      responses:
        "200":
          description: OK
          schema:
            type: image
      summary: 获取头像
      tags:
      - 头像模块
  /login:
    post:
      consumes:
      - application/json
      description: 支持使用`用户名`/`邮箱`+`密码`来登录
      parameters:
      - description: params
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/go-gravatar_api_v1.LoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/go-gravatar_api_v1.LoginResponse'
      summary: 账号登录
      tags:
      - 用户模块
  /register:
    post:
      consumes:
      - application/json
      description: 目前只支持邮箱注册
      parameters:
      - description: params
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/go-gravatar_api_v1.RegisterRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/go-gravatar_api_v1.Response'
      summary: 用户注册
      tags:
      - 用户模块
  /reset:
    post:
      consumes:
      - application/json
      description: 目前只支持邮箱重置
      parameters:
      - description: params
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/go-gravatar_api_v1.ResetRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/go-gravatar_api_v1.Response'
      summary: 重置密码
      tags:
      - 用户模块
  /user:
    delete:
      consumes:
      - application/json
      description: 删除用户
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/go-gravatar_api_v1.Response'
      security:
      - Bearer: []
      summary: 删除用户
      tags:
      - 用户模块
    get:
      consumes:
      - application/json
      description: 获取用户信息(不包括用户头像)
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/go-gravatar_api_v1.GetProfileResponse'
      security:
      - Bearer: []
      summary: 获取用户信息
      tags:
      - 用户模块
    put:
      consumes:
      - application/json
      description: 修改用户信息(不包括用户头像)
      parameters:
      - description: params
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/go-gravatar_api_v1.UpdateProfileRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/go-gravatar_api_v1.Response'
      security:
      - Bearer: []
      summary: 修改用户信息
      tags:
      - 用户模块
securityDefinitions:
  Bearer:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
