name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  lint:
    name: Lint Code
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.18'  # 使用你需要的Go版本

      - name: Run GolangCI-Lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.45.2  # 使用你需要的GolangCI-Lint版本
          args: --timeout=5m

  build:
    name: Build Project
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.18'  # 使用你需要的Go版本

      - name: Build Project
        run: go build -v ./...

  test:
    name: Run Tests
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.18'  # 使用你需要的Go版本

      - name: Run Tests
        run: go test -v ./...

  # 可选：如果你需要将构建产物发布到某个地方（比如Docker Hub或者GitHub Releases）
  # deploy:
  #   name: Deploy to [目标]
  #   runs-on: ubuntu-latest
  #   needs: test
  #   steps:
  #     - name: Checkout Code
  #       uses: actions/checkout@v2
  #
  #     - name: Set up Go
  #       uses: actions/setup-go@v2
  #       with:
  #         go-version: '1.18'  # 使用你需要的Go版本
  #
  #     # 添加部署步骤
  #     # 例如，构建Docker镜像并推送到Docker Hub
  #     - name: Build and Push Docker Image
  #       uses: docker/build-push-action@v2
  #       with:
  #         context: .
  #         push: true
  #         tags: yourdockerhubusername/your-repo-name:latest
  #       env:
  #         DOCKER_BUILDKIT: 1
  #         DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  #         DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
